### ISSUE TITLE
pip install pyltp安装失败 win10 64位 Python 2.7.13 :: Anaconda 4.3.0 (64-bit)

### ISSUE THREAD

**Issue by xinan711456** [HuangFJ/pyltp#3]
无法使用哈工大语言云的pyltp，请帮忙。
 error: INCLUDE environment variable is empty

  ----------------------------------------
  Failed building wheel for pyltp
  Running setup.py clean for pyltp
Failed to build pyltp
Installing collected packages: pyltp
  Running setup.py install for pyltp ... error
    Complete output from command D:\unclosed\Anaconda27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\30913\\appdata\\local\\temp\\pip-build-r8b0bt\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\30913\appdata\local\temp\pip-ftqiqy-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'pyltp' extension
    error: INCLUDE environment variable is empty

    ----------------------------------------
Command "D:\unclosed\Anaconda27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\30913\\appdata\\local\\temp\\pip-build-r8b0bt\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\30913\appdata\local\temp\pip-ftqiqy-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\30913\appdata\local\temp\pip-build-r8b0bt\pyltp\

**Comment by pogevip** [comment]
不知道你有没有解决，我遇到了同样的问题

**Comment by xinan711456** [comment]
https://github.com/HIT-SCIR/pyltp/issues/108
pip install pyltp即可（版本0.1.9）
（1）已成功在python2和python3上安装pyltp
（2）python2需要vcforpython2.7（根据报错找到相应软件安装即可）
（3）python3需要visualcppbuildtools_full2015（（根据报错找到相应软件安装即可））
（4）如果还是不行，清理pip cache内容重新安装：c:\用户(你的用户名)\AppData\Local\pip\cache\目录
（5）成功在python2和python3上安装成功pyltp，是没有pyltp文件夹的，只有pyltp.pyc和pyltp-info文件夹
